"""initial schema

Revision ID: 0002_initial_schema
Revises: 0001_extensions
Create Date: 2026-08-30 14:48:49.366972
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_initial_schema'
down_revision: str | None = '0001_extensions'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country_code', sa.String(length=2), server_default='IN', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Kolkata', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('slug', name=op.f('uq_cities_slug'))
    )
    op.create_index('ix_cities_is_active_display_order', 'cities', ['is_active', 'display_order'], unique=False)
    op.create_table('formats',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('surcharge_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.CheckConstraint('surcharge_minor >= 0', name=op.f('ck_formats_surcharge_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formats')),
    sa.UniqueConstraint('code', name=op.f('uq_formats_code'))
    )
    op.create_table('genres',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_genres_slug'))
    )
    op.create_table('languages',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('native_name', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('code', name=op.f('uq_languages_code'))
    )
    op.create_table('offers',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('offer_type', sa.Enum('percent', 'flat', 'buy_n_get_m', name='offer_type'), nullable=False),
    sa.Column('percent_off', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('flat_off_minor', sa.Integer(), nullable=True),
    sa.Column('buy_quantity', sa.Integer(), nullable=True),
    sa.Column('get_quantity', sa.Integer(), nullable=True),
    sa.Column('max_discount_minor', sa.Integer(), nullable=True),
    sa.Column('min_order_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_limit_total', sa.Integer(), nullable=True),
    sa.Column('usage_limit_per_user', sa.Integer(), server_default='1', nullable=False),
    sa.Column('redeemed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_stackable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(offer_type <> 'percent' OR (percent_off IS NOT NULL AND percent_off > 0 AND percent_off <= 100)) AND (offer_type <> 'flat' OR (flat_off_minor IS NOT NULL AND flat_off_minor > 0)) AND (offer_type <> 'buy_n_get_m' OR (buy_quantity IS NOT NULL AND get_quantity IS NOT NULL))", name=op.f('ck_offers_offer_value_matches_type')),
    sa.CheckConstraint('redeemed_count >= 0', name=op.f('ck_offers_redeemed_count_non_negative')),
    sa.CheckConstraint('valid_until > valid_from', name=op.f('ck_offers_valid_window_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('code', name=op.f('uq_offers_code'))
    )
    op.create_index('ix_offers_is_active_valid_until', 'offers', ['is_active', 'valid_until'], unique=False)
    op.create_table('people',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('slug', name=op.f('uq_people_slug'))
    )
    op.create_index('ix_people_name_trgm', 'people', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('movies',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('original_title', sa.String(length=300), nullable=True),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('tagline', sa.String(length=400), nullable=True),
    sa.Column('synopsis', sa.Text(), server_default='', nullable=False),
    sa.Column('runtime_minutes', sa.Integer(), nullable=False),
    sa.Column('certification', sa.String(length=16), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('coming_soon', 'now_showing', 'archived', name='movie_status'), server_default='coming_soon', nullable=False),
    sa.Column('original_language_id', sa.Uuid(), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('backdrop_url', sa.Text(), nullable=True),
    sa.Column('trailer_url', sa.Text(), nullable=True),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('popularity_score', sa.Numeric(precision=8, scale=3), server_default='0', nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_summary_generated_at', sa.Date(), nullable=True),
    sa.Column('ai_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating_average is null or (rating_average >= 0 and rating_average <= 10)', name=op.f('ck_movies_rating_average_range')),
    sa.CheckConstraint('runtime_minutes > 0', name=op.f('ck_movies_runtime_positive')),
    sa.ForeignKeyConstraint(['original_language_id'], ['languages.id'], name=op.f('fk_movies_original_language_id_languages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies')),
    sa.UniqueConstraint('slug', name=op.f('uq_movies_slug'))
    )
    op.create_index('ix_movies_popularity_score', 'movies', ['popularity_score'], unique=False)
    op.create_index('ix_movies_status_release_date', 'movies', ['status', 'release_date'], unique=False)
    op.create_index('ix_movies_title_trgm', 'movies', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'cinema_operator', 'admin', name='user_role'), server_default='customer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_city_id', sa.Uuid(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_city_id'], ['cities.id'], name=op.f('fk_users_default_city_id_cities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_index('ix_users_default_city_id', 'users', ['default_city_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('cinemas',
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('address_line', sa.Text(), nullable=False),
    sa.Column('locality', sa.String(length=160), nullable=True),
    sa.Column('pincode', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Kolkata', nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('operator_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_cinemas_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_user_id'], ['users.id'], name=op.f('fk_cinemas_operator_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cinemas')),
    sa.UniqueConstraint('slug', name=op.f('uq_cinemas_slug'))
    )
    op.create_index('ix_cinemas_city_id_is_active', 'cinemas', ['city_id', 'is_active'], unique=False)
    op.create_index('ix_cinemas_operator_user_id', 'cinemas', ['operator_user_id'], unique=False)
    op.create_table('domain_events',
    sa.Column('aggregate_type', sa.String(length=40), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_domain_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_events'))
    )
    op.create_index('ix_domain_events_aggregate_type_aggregate_id', 'domain_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_domain_events_created_at', 'domain_events', ['created_at'], unique=False)
    op.create_index('ix_domain_events_event_type_created_at', 'domain_events', ['event_type', 'created_at'], unique=False)
    op.create_table('movie_credits',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('credit_type', sa.Enum('cast', 'crew', name='credit_type'), nullable=False),
    sa.Column('character_name', sa.String(length=200), nullable=True),
    sa.Column('job', sa.String(length=120), nullable=True),
    sa.Column('billing_order', sa.SmallInteger(), server_default='99', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_credits_movie_id_movies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_movie_credits_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie_credits')),
    sa.UniqueConstraint('movie_id', 'person_id', 'credit_type', 'job', 'character_name', name='uq_movie_credits_identity', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_movie_credits_movie_id_billing_order', 'movie_credits', ['movie_id', 'billing_order'], unique=False)
    op.create_index('ix_movie_credits_person_id', 'movie_credits', ['person_id'], unique=False)
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_movie_genres_genre_id_genres'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_genres_movie_id_movies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id', name=op.f('pk_movie_genres'))
    )
    op.create_table('movie_languages',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_movie_languages_language_id_languages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_languages_movie_id_movies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'language_id', name=op.f('pk_movie_languages'))
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_from_id', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.ForeignKeyConstraint(['rotated_from_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_rotated_from_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    op.create_index('ix_refresh_tokens_user_id_expires_at', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_table('fnb_items',
    sa.Column('cinema_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_vegetarian', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_minor >= 0', name=op.f('ck_fnb_items_price_non_negative')),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], name=op.f('fk_fnb_items_cinema_id_cinemas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fnb_items')),
    sa.UniqueConstraint('cinema_id', 'name', name='uq_fnb_items_cinema_id_name')
    )
    op.create_index('ix_fnb_items_cinema_id_is_available', 'fnb_items', ['cinema_id', 'is_available'], unique=False)
    op.create_table('screens',
    sa.Column('cinema_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('screen_number', sa.Integer(), nullable=False),
    sa.Column('supported_formats', postgresql.JSONB(astext_type=sa.Text()), server_default='["2D"]', nullable=False),
    sa.Column('sound_system', sa.String(length=80), nullable=True),
    sa.Column('total_seats', sa.Integer(), server_default='0', nullable=False),
    sa.Column('layout_meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('layout_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_seats >= 0', name=op.f('ck_screens_total_seats_non_negative')),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], name=op.f('fk_screens_cinema_id_cinemas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screens')),
    sa.UniqueConstraint('cinema_id', 'screen_number', name='uq_screens_cinema_id_screen_number')
    )
    op.create_index('ix_screens_cinema_id_is_active', 'screens', ['cinema_id', 'is_active'], unique=False)
    op.create_table('seat_categories',
    sa.Column('cinema_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_price_minor', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_price_minor >= 0', name=op.f('ck_seat_categories_default_price_non_negative')),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], name=op.f('fk_seat_categories_cinema_id_cinemas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_categories')),
    sa.UniqueConstraint('cinema_id', 'code', name='uq_seat_categories_cinema_id_code')
    )
    op.create_table('seats',
    sa.Column('screen_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('row_label', sa.String(length=4), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('column_index', sa.Integer(), nullable=False),
    sa.Column('is_aisle', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_wheelchair_accessible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_companion', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('row_index >= 0', name=op.f('ck_seats_row_index_non_negative')),
    sa.CheckConstraint('seat_number > 0', name=op.f('ck_seats_seat_number_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['seat_categories.id'], name=op.f('fk_seats_category_id_seat_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], name=op.f('fk_seats_screen_id_screens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('screen_id', 'row_label', 'seat_number', name='uq_seats_screen_id_row_label_seat_number')
    )
    op.create_index('ix_seats_category_id', 'seats', ['category_id'], unique=False)
    op.create_index('ix_seats_screen_id_row_index_column_index', 'seats', ['screen_id', 'row_index', 'column_index'], unique=False)
    op.create_table('shows',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('screen_id', sa.Uuid(), nullable=False),
    sa.Column('format_id', sa.Uuid(), nullable=False),
    sa.Column('audio_language_id', sa.Uuid(), nullable=False),
    sa.Column('subtitle_language_id', sa.Uuid(), nullable=True),
    sa.Column('cinema_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('show_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'open', 'closed', 'cancelled', 'completed', name='show_status'), server_default='scheduled', nullable=False),
    sa.Column('sales_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_close_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('screen_layout_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('total_seats', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_seats', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('screen_id'), '='), (sa.text('tstzrange(starts_at, ends_at)'), '&&'), where=sa.text("status <> 'cancelled'"), using='gist', name='ex_shows_screen_no_overlap'),
    sa.CheckConstraint('available_seats <= total_seats', name=op.f('ck_shows_available_within_total')),
    sa.CheckConstraint('available_seats >= 0', name=op.f('ck_shows_available_seats_non_negative')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_shows_ends_after_starts')),
    sa.ForeignKeyConstraint(['audio_language_id'], ['languages.id'], name=op.f('fk_shows_audio_language_id_languages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], name=op.f('fk_shows_cinema_id_cinemas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_shows_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['format_id'], ['formats.id'], name=op.f('fk_shows_format_id_formats'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_shows_movie_id_movies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], name=op.f('fk_shows_screen_id_screens'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subtitle_language_id'], ['languages.id'], name=op.f('fk_shows_subtitle_language_id_languages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shows')),
    sa.UniqueConstraint('screen_id', 'starts_at', name='uq_shows_screen_id_starts_at')
    )
    op.create_index('ix_shows_cinema_id_show_date_starts_at', 'shows', ['cinema_id', 'show_date', 'starts_at'], unique=False)
    op.create_index('ix_shows_city_id_movie_id_show_date', 'shows', ['city_id', 'movie_id', 'show_date'], unique=False)
    op.create_index('ix_shows_screen_id_starts_at', 'shows', ['screen_id', 'starts_at'], unique=False)
    op.create_index('ix_shows_status_starts_at', 'shows', ['status', 'starts_at'], unique=False)
    op.create_table('seat_holds',
    sa.Column('show_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'converted', 'released', 'expired', name='hold_status'), server_default='active', nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.CheckConstraint('seat_count > 0', name=op.f('ck_seat_holds_seat_count_positive')),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_seat_holds_show_id_shows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_seat_holds_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_holds'))
    )
    op.create_index('ix_seat_holds_session_key', 'seat_holds', ['session_key'], unique=False)
    op.create_index('ix_seat_holds_show_id_status', 'seat_holds', ['show_id', 'status'], unique=False)
    op.create_index('ix_seat_holds_status_expires_at', 'seat_holds', ['status', 'expires_at'], unique=False)
    op.create_index('ix_seat_holds_user_id', 'seat_holds', ['user_id'], unique=False)
    op.create_table('show_prices',
    sa.Column('show_id', sa.Uuid(), nullable=False),
    sa.Column('seat_category_id', sa.Uuid(), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('ai_suggested_price_minor', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.CheckConstraint('price_minor >= 0', name=op.f('ck_show_prices_price_non_negative')),
    sa.ForeignKeyConstraint(['seat_category_id'], ['seat_categories.id'], name=op.f('fk_show_prices_seat_category_id_seat_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_show_prices_show_id_shows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_show_prices')),
    sa.UniqueConstraint('show_id', 'seat_category_id', name='uq_show_prices_show_id_seat_category_id')
    )
    op.create_table('bookings',
    sa.Column('booking_reference', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('show_id', sa.Uuid(), nullable=False),
    sa.Column('hold_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'payment_pending', 'confirmed', 'payment_failed', 'expired', 'cancelled', 'refunded', 'revoked', name='booking_status'), server_default='draft', nullable=False),
    sa.Column('seat_count', sa.SmallInteger(), nullable=False),
    sa.Column('ticket_subtotal_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fnb_subtotal_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('convenience_fee_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tax_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('price_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('offer_code', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('payment_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('qr_payload', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_seats', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('booking_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('checked_in_seats >= 0 AND checked_in_seats <= seat_count', name=op.f('ck_bookings_checked_in_within_seat_count')),
    sa.CheckConstraint('discount_minor >= 0', name=op.f('ck_bookings_discount_non_negative')),
    sa.CheckConstraint('seat_count > 0', name=op.f('ck_bookings_seat_count_positive')),
    sa.CheckConstraint('total_minor = ticket_subtotal_minor + fnb_subtotal_minor - discount_minor + convenience_fee_minor + tax_minor', name=op.f('ck_bookings_total_is_sum_of_parts')),
    sa.CheckConstraint('total_minor >= 0', name=op.f('ck_bookings_total_non_negative')),
    sa.ForeignKeyConstraint(['hold_id'], ['seat_holds.id'], name=op.f('fk_bookings_hold_id_seat_holds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_bookings_offer_id_offers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_bookings_show_id_shows'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('booking_reference', name=op.f('uq_bookings_booking_reference'))
    )
    op.create_index('ix_bookings_hold_id', 'bookings', ['hold_id'], unique=False)
    op.create_index('ix_bookings_show_id_status', 'bookings', ['show_id', 'status'], unique=False)
    op.create_index('ix_bookings_status_payment_deadline_at', 'bookings', ['status', 'payment_deadline_at'], unique=False)
    op.create_index('ix_bookings_user_id_created_at', 'bookings', ['user_id', 'created_at'], unique=False)
    op.create_table('booking_fnb_items',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('fnb_item_id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('unit_price_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_booking_fnb_items_quantity_positive')),
    sa.CheckConstraint('total_minor = unit_price_minor * quantity', name=op.f('ck_booking_fnb_items_line_total_consistent')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_fnb_items_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fnb_item_id'], ['fnb_items.id'], name=op.f('fk_booking_fnb_items_fnb_item_id_fnb_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_fnb_items')),
    sa.UniqueConstraint('booking_id', 'fnb_item_id', name='uq_booking_fnb_items_booking_id_fnb_item_id')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.SmallInteger(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_idempotency_keys_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_keys_scope_key')
    )
    op.create_index('ix_idempotency_keys_created_at', 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'sms', 'push', 'in_app', name='notification_channel'), nullable=False),
    sa.Column('template', sa.String(length=80), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='notification_status'), server_default='queued', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_notifications_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_booking_id', 'notifications', ['booking_id'], unique=False)
    op.create_index('ix_notifications_status_scheduled_for', 'notifications', ['status', 'scheduled_for'], unique=False)
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('offer_redemptions',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('discount_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.CheckConstraint('discount_minor >= 0', name=op.f('ck_offer_redemptions_discount_non_negative')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_offer_redemptions_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_offer_redemptions_offer_id_offers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_offer_redemptions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_redemptions')),
    sa.UniqueConstraint('booking_id', name='uq_offer_redemptions_booking_id')
    )
    op.create_index('ix_offer_redemptions_offer_id_user_id', 'offer_redemptions', ['offer_id', 'user_id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=128), nullable=False),
    sa.Column('gateway_payment_id', sa.String(length=128), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('amount_refunded_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('created', 'processing', 'authorized', 'captured', 'failed', 'refund_pending', 'refunded', 'partially_refunded', name='payment_status'), server_default='created', nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('failure_code', sa.String(length=60), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_auto_refund', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('gateway_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_payments_amount_positive')),
    sa.CheckConstraint('amount_refunded_minor >= 0 AND amount_refunded_minor <= amount_minor', name=op.f('ck_payments_refunded_within_amount')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('gateway', 'gateway_order_id', name='uq_payments_gateway_gateway_order_id')
    )
    op.create_index('ix_payments_booking_id_status', 'payments', ['booking_id', 'status'], unique=False)
    op.create_index('ix_payments_requires_auto_refund', 'payments', ['requires_auto_refund'], unique=False)
    op.create_index('ix_payments_status_created_at', 'payments', ['status', 'created_at'], unique=False)
    op.create_table('reviews',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('is_spoiler', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('helpful_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ai_aspects', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ai_sentiment', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ai_processed_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating between 1 and 10', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_reviews_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_reviews_movie_id_movies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('movie_id', 'user_id', name='uq_reviews_movie_id_user_id')
    )
    op.create_index('ix_reviews_movie_id_created_at', 'reviews', ['movie_id', 'created_at'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_table('show_seats',
    sa.Column('show_id', sa.Uuid(), nullable=False),
    sa.Column('seat_id', sa.Uuid(), nullable=False),
    sa.Column('seat_category_id', sa.Uuid(), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('available', 'held', 'booked', 'blocked', name='show_seat_status'), server_default='available', nullable=False),
    sa.Column('hold_id', sa.Uuid(), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('blocked_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'available') OR (hold_id IS NULL AND booking_id IS NULL)", name=op.f('ck_show_seats_available_is_clean')),
    sa.CheckConstraint("(status <> 'booked') OR (booking_id IS NOT NULL)", name=op.f('ck_show_seats_booked_requires_booking')),
    sa.CheckConstraint("(status <> 'held') OR (hold_id IS NOT NULL AND hold_expires_at IS NOT NULL)", name=op.f('ck_show_seats_held_requires_hold')),
    sa.CheckConstraint('price_minor >= 0', name=op.f('ck_show_seats_price_non_negative')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_show_seats_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hold_id'], ['seat_holds.id'], name=op.f('fk_show_seats_hold_id_seat_holds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seat_category_id'], ['seat_categories.id'], name=op.f('fk_show_seats_seat_category_id_seat_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_show_seats_seat_id_seats'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_show_seats_show_id_shows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_show_seats')),
    sa.UniqueConstraint('show_id', 'seat_id', name='uq_show_seats_show_id_seat_id')
    )
    op.create_index('ix_show_seats_booking_id', 'show_seats', ['booking_id'], unique=False)
    op.create_index('ix_show_seats_hold_id', 'show_seats', ['hold_id'], unique=False)
    op.create_index('ix_show_seats_show_id_status', 'show_seats', ['show_id', 'status'], unique=False)
    op.create_table('booking_seats',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('show_seat_id', sa.Uuid(), nullable=False),
    sa.Column('seat_id', sa.Uuid(), nullable=False),
    sa.Column('seat_label', sa.String(length=12), nullable=False),
    sa.Column('seat_category_name', sa.String(length=80), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.CheckConstraint('price_minor >= 0', name=op.f('ck_booking_seats_price_non_negative')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_seats_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_booking_seats_seat_id_seats'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['show_seat_id'], ['show_seats.id'], name=op.f('fk_booking_seats_show_seat_id_show_seats'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_seats'))
    )
    op.create_index('ix_booking_seats_booking_id', 'booking_seats', ['booking_id'], unique=False)
    op.create_index('uq_booking_seats_active_show_seat', 'booking_seats', ['show_seat_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('payment_events',
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_events_payment_id_payments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events')),
    sa.UniqueConstraint('gateway', 'event_id', name='uq_payment_events_gateway_event_id')
    )
    op.create_index('ix_payment_events_payment_id_received_at', 'payment_events', ['payment_id', 'received_at'], unique=False)
    op.create_index('ix_payment_events_processed_at', 'payment_events', ['processed_at'], unique=False)
    op.create_table('refunds',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='refund_status'), server_default='pending', nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('gateway_refund_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_refunds_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('idempotency_key', name='uq_refunds_idempotency_key')
    )
    op.create_index('ix_refunds_booking_id', 'refunds', ['booking_id'], unique=False)
    op.create_index('ix_refunds_status', 'refunds', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refunds_status', table_name='refunds')
    op.drop_index('ix_refunds_booking_id', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_payment_events_processed_at', table_name='payment_events')
    op.drop_index('ix_payment_events_payment_id_received_at', table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index('uq_booking_seats_active_show_seat', table_name='booking_seats', postgresql_where=sa.text('is_active'))
    op.drop_index('ix_booking_seats_booking_id', table_name='booking_seats')
    op.drop_table('booking_seats')
    op.drop_index('ix_show_seats_show_id_status', table_name='show_seats')
    op.drop_index('ix_show_seats_hold_id', table_name='show_seats')
    op.drop_index('ix_show_seats_booking_id', table_name='show_seats')
    op.drop_table('show_seats')
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index('ix_reviews_movie_id_created_at', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_payments_status_created_at', table_name='payments')
    op.drop_index('ix_payments_requires_auto_refund', table_name='payments')
    op.drop_index('ix_payments_booking_id_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_offer_redemptions_offer_id_user_id', table_name='offer_redemptions')
    op.drop_table('offer_redemptions')
    op.drop_index('ix_notifications_user_id_created_at', table_name='notifications')
    op.drop_index('ix_notifications_status_scheduled_for', table_name='notifications')
    op.drop_index('ix_notifications_booking_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_idempotency_keys_created_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('booking_fnb_items')
    op.drop_index('ix_bookings_user_id_created_at', table_name='bookings')
    op.drop_index('ix_bookings_status_payment_deadline_at', table_name='bookings')
    op.drop_index('ix_bookings_show_id_status', table_name='bookings')
    op.drop_index('ix_bookings_hold_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('show_prices')
    op.drop_index('ix_seat_holds_user_id', table_name='seat_holds')
    op.drop_index('ix_seat_holds_status_expires_at', table_name='seat_holds')
    op.drop_index('ix_seat_holds_show_id_status', table_name='seat_holds')
    op.drop_index('ix_seat_holds_session_key', table_name='seat_holds')
    op.drop_table('seat_holds')
    op.drop_index('ix_shows_status_starts_at', table_name='shows')
    op.drop_index('ix_shows_screen_id_starts_at', table_name='shows')
    op.drop_index('ix_shows_city_id_movie_id_show_date', table_name='shows')
    op.drop_index('ix_shows_cinema_id_show_date_starts_at', table_name='shows')
    op.drop_table('shows')
    op.drop_index('ix_seats_screen_id_row_index_column_index', table_name='seats')
    op.drop_index('ix_seats_category_id', table_name='seats')
    op.drop_table('seats')
    op.drop_table('seat_categories')
    op.drop_index('ix_screens_cinema_id_is_active', table_name='screens')
    op.drop_table('screens')
    op.drop_index('ix_fnb_items_cinema_id_is_available', table_name='fnb_items')
    op.drop_table('fnb_items')
    op.drop_index('ix_refresh_tokens_user_id_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('movie_languages')
    op.drop_table('movie_genres')
    op.drop_index('ix_movie_credits_person_id', table_name='movie_credits')
    op.drop_index('ix_movie_credits_movie_id_billing_order', table_name='movie_credits')
    op.drop_table('movie_credits')
    op.drop_index('ix_domain_events_event_type_created_at', table_name='domain_events')
    op.drop_index('ix_domain_events_created_at', table_name='domain_events')
    op.drop_index('ix_domain_events_aggregate_type_aggregate_id', table_name='domain_events')
    op.drop_table('domain_events')
    op.drop_index('ix_cinemas_operator_user_id', table_name='cinemas')
    op.drop_index('ix_cinemas_city_id_is_active', table_name='cinemas')
    op.drop_table('cinemas')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_default_city_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_movies_title_trgm', table_name='movies', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_movies_status_release_date', table_name='movies')
    op.drop_index('ix_movies_popularity_score', table_name='movies')
    op.drop_table('movies')
    op.drop_index('ix_people_name_trgm', table_name='people', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('people')
    op.drop_index('ix_offers_is_active_valid_until', table_name='offers')
    op.drop_table('offers')
    op.drop_table('languages')
    op.drop_table('genres')
    op.drop_table('formats')
    op.drop_index('ix_cities_is_active_display_order', table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
