"""movie provenance

Revision ID: 0004_movie_provenance
Revises: 0003_payment_cancelled
Create Date: 2026-08-30 17:59:21.762163
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0004_movie_provenance'
down_revision: str | None = '0003_payment_cancelled'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('movies', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.create_index('ix_movies_created_by_user_id', 'movies', ['created_by_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_movies_created_by_user_id_users'), 'movies', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('offer_redemptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer_redemptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-30 10:02:40.909273+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_movies_created_by_user_id_users'), 'movies', type_='foreignkey')
    op.drop_index('ix_movies_created_by_user_id', table_name='movies')
    op.drop_column('movies', 'created_by_user_id')
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-30 10:02:40.909273+00'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
