"""selection vs kept holds

Revision ID: 0005_kept_holds
Revises: 0004_movie_provenance
Create Date: 2026-08-30 19:25:08.238829
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0005_kept_holds'
down_revision: str | None = '0004_movie_provenance'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat_holds', sa.Column('keep_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat_holds', 'keep_requested_at')
    # ### end Alembic commands ###
